### PR TITLE
updated link to HAML Docs

### PR DESCRIPTION
**Pull request by ghost**
it's on HAML.info now, http://haml.info/docs/yardoc/file.HAML_REFERENCE.html

### CODE REVIEW

**Comment by ghost** [comment]
NONONONO-
too much commits, only the first one is for this pullreq...

**Comment by norman** [comment]
Please don't fork this project and start distributing it under another name just to make it work with Luvit and to reformat the documentation and examples. Make your own library that uses Lua Haml, or send pull requests to add whatever you need to Lua Haml, which I'd probably be willing to accept.

Otherwise you're putting two branches of the source code out there that will need to be maintained. When somebody using Luvit has issues with Haml, who's going to fix them? Where do they report them?

Nothing in the license prevents you from doing this, but that doesn't mean you have to be inconsiderate. The way you've done this makes it looks like an attempt to take credit for somebody else's work.

**Comment by agladysh** [comment]
Ugh. One more example of why Luvit's incompatible ecosystem is poisonous for the community. :-(

**Comment by norman** [comment]
@agladysh what makes me really upset is that I would have no problem adding support for Luvit, especially if somebody is willing to do the work. I don't personally use it, but as long as it doesn't break anything I'd be totally happy to help make it work and continue to support it. It's not only inconsiderate but also unnecessary.

**Comment by ghost** [comment]
It's ¡Work in progress! kinda thing, i'll put all the credits, the license and everything later, first thing is to make it work with luvit/lum.

The fact that it's forked acly gives you a lot of credit, and your project is in the readme as well.

If some errors may popup on my side i'll prbly fix them and send a pullreq back here if applicable. If somewhere here in issues comes new bugrep, i'll notice.

I'm kinda new to Lua and don't really know if it's community places [personal] relations over the code, but i don't.

---

If you really think same codebase is not worth to be in two different-targeted repos, i'll just start anew from scratch, wanted to make sass/less/stylus bindings as well, so maybe it's better to have separate project anyway.

**Comment by norman** [comment]
> i'll put all the credits, the license and everything later

The license says:

> Permission is hereby granted, free of charge, to any person obtaining a copy of
> this software and associated documentation files (the "Software"), to deal in
> the Software without restriction, including without limitation the rights to
> use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
> the Software, and to permit persons to whom the Software is furnished to do so,
> subject to the following conditions:
> 
> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

You are legally required to put it in now. Otherwise, you may not distribute my work. Having a public repository on Github counts as distribution.

> The fact that it's forked acly gives you a lot of credit, and your project is in the readme as well.

No, it doesn't. You know what does though? The License that I added to my original work.

> If you really think same codebase is not worth to be in two different-targeted repos, i'll just start anew from scratch, wanted to make sass/less/stylus bindings as well, so maybe it's better to have separate project anyway.

Yes, please start from scratch. Just to help you out, I'll be sure to keep an eye on your project and will send you a reminder if any of my copyrighted code enters into your project without attribution.

> I'm kinda new to Lua and don't really know if it's community places [personal] relations over the code, but i don't.

What the hell are you talking about? Our relationship currently stands at this: I created a copyrighted work, and you are stealing it. Don't try to make this sound like I have some sort of personal problem. You are the one doing something legally and morally wrong.

Just to be clear: You have the legal right to reuse my work as long as you license it. If you do that, we're fine and I won't bother you. However, I think your approach here is 100% wrong. If you wanted to get Haml working nicely on Luvit, why didn't you just do the work to add support and send me a patch? 

I already know the answer though. Your primary interest isn't getting this to run on Luvit. You forked my work, removed my name from the credits and removed all the project setup files so that you could have "your own project" that you're in charge of, and get recognition for it. If you want recognition from the community though, you're not going to get it by taking the easy way and stealing other people's work - at least not the kind of recognition you're hoping you'll get.

**Comment by ghost** [comment]
orevuar

**Comment by norman** [comment]
Ok, thank you for taking down your fork.

**Pull request closed without merging**
